### PR TITLE
constexpr -> SBE_CONSTEXPR

### PR DESCRIPTION
**Pull request by lygstate**

### CODE REVIEW

**Comment by mjpt777** [comment]
This introduces more warnings to the build rather than reducing.

**Comment by lygstate** [comment]
What warning it cause? Old compiler doesn't have constexpr

**Comment by mjpt777** [comment]
> What warning it cause?
https://github.com/real-logic/simple-binary-encoding/pull/793/checks?check_run_id=715960514

**Comment by lygstate** [comment]
There is another fixes about the warning
The warning was hidden by constexpr

**Pull request merged**
