### PR TITLE
[c++] Improved field generation

### PR DESCRIPTION
**Pull request by ksergey**
Added std::string_view getter/setter for string-like fields
Added non-const raw access for array like fields

### CODE REVIEW

**Comment by mjpt777** [comment]
I have merged but this has some issues. What if the string or string view is shorter than the array? The Java codec deals with this by zero padding the remainder and doing a min on the copy for length of view and length of array.

**Comment by ksergey** [comment]
>>What if the string or string view is shorter than the array?
It's UB. Actually I added `std::string_view` in the same way as `std::string` was added. So, user should solve this case by themself.

**Comment by ksergey** [comment]
I think we could add deactivatable via macros check `value.length() == fieldLength()` inside `putField(...)` methods.

**Comment by mjpt777** [comment]
Identifying this as UB feels wrong and error prone. The existing string approach was also wrong in this.

**Comment by tmontgomery** [comment]
`std::string_view` is C++17. I don't think we want to go there just yet.

**Comment by mjpt777** [comment]
@tmontgomery the code is guarded for C++ 17 so only compiled when available.

**Comment by tmontgomery** [comment]
And, yes, if the string is short, it should null pad.

**Comment by tmontgomery** [comment]
@mjpt777 yes, I understand that. I would, though, say that to avoid noise and the fact that there is very little reason to use it yet that there is no compelling reason to do it at this time.

**Comment by ksergey** [comment]
@tmontgomery why short string should be null padded? Is string getter should be aware of this (i.e. return string with length less than field length)?

**Comment by tmontgomery** [comment]
It probably should be encoding specific what to pad with. And it should be compatible with what Java does right now.

The getter is always going to be a specific length. It just may have encoding specific nulls, etc. The setter is the one to determine what to do with the string/string_view is too short.

**Comment by mjpt777** [comment]
The spec example suggests null padding.

https://github.com/FIXTradingCommunity/fix-simple-binary-encoding/blob/master/v1-0-STANDARD/doc/02FieldEncoding.md#examples-of-fixed-length-character-arrays

**Comment by tmontgomery** [comment]
I've added length checks and handling via 825e0c48

**Comment by tmontgomery** [comment]
checks for `const char *` versions are not needed. Those are the sharp knives. Know how to use them. `std:string` and `std::string_view` are for those who need their hands held while they cross the street.

**Pull request merged**
