### PR TITLE
Add support of constexpr, noexcept and move semantic for Visual Studio 2015+

### PR DESCRIPTION
**Pull request by ujos**
Since Visual Studio 2015 constexpr and noexcept keywords are supported. Given commit enables those features.

### CODE REVIEW

**Comment by mjpt777** [comment]
Is this still relevant? @tmontgomery do you have a view on this?

**Comment by tmontgomery** [comment]
Quite a few changes since. No updates.... closing.

**Comment by ujos** [comment]
Guys, you do not need my comments to determine is it relevant or not. `constexpr` and `noexcept` is still part of C++ standard. 

Also changes count is not criterion of either merge request should be closed or not.

**Comment by tmontgomery** [comment]
Not referring to changes in the PR. Changes to SBE, the generator, etc.

**Pull request closed without merging**
