### PR TITLE
Add a generator for C

### PR DESCRIPTION
**Pull request by Niko-Klaiber**
This PR does not support OTF decoding for C. I converted the tests for C++ that do not involve OTF decoding to use the stubs generated for C.

### CODE REVIEW

**Comment by tmontgomery** [comment]
Made some major changes to the C++ generator (such as removing sbe.h) that might be good to review and see if they affect this.

**Comment by nikoJP** [comment]
I applied your most recent changes.

**Comment by Taaughty** [comment]
Hello tmontgomery, I applied the most recent changes to my file.
Thank you.

**Comment by tmontgomery** [comment]
Sorry it took a while to get to a proper review. This looks pretty good. Thanks!

**Pull request merged**
