### PR TITLE
Remove warning in CppGenerator.java by refactoring out a FormatterWra…

### PR DESCRIPTION
**Pull request by lygstate**
…pper

### CODE REVIEW

**Comment by mjpt777** [comment]
Warning does this remove?

**Comment by lygstate** [comment]
```
        new Formatter(sb).format("\n" +
```
cause

Resource leak: '<unassigned Closeable value>' is not closed at this location

**Comment by mjpt777** [comment]
Can you explain the resource leak?

**Comment by lygstate** [comment]
java report this, not me, i don't know about resource leak.

**Comment by lygstate** [comment]
Resource leak: '<unassigned Closeable value>' is not closed at this location

**Comment by lygstate** [comment]
https://stackoverflow.com/questions/31018742/resource-leak-rset-is-not-closed-at-this-location

**Comment by mjpt777** [comment]
How is it reported? What tool and test are you running?

**Comment by lygstate** [comment]
vscode + redhat Java tool

**Comment by mjpt777** [comment]
I don't see the leak, and all the PR does is obfuscate the code so it is probably fooling the tool.

**Comment by mjpt777** [comment]
What line number in the file are you getting the report at?

**Comment by lygstate** [comment]
See the patch, everyline with a new Formatter.
I didn't fool the tool, I just use StringBuffer.append instead new Formatter.
The Formatter are already removed

**Comment by mjpt777** [comment]
The warning is incorrect plus the patch massively increases allocation.

**Pull request closed without merging**
