### PR TITLE
[C++] Methods to calculate the length of an SBE message

### PR DESCRIPTION
**Pull request by agmt**
Implements: https://github.com/real-logic/simple-binary-encoding/issues/291

### CODE REVIEW

**Comment by mjpt777** [comment]
Will look in more detail in at a later date. Got a bit too much on at the minute.

One thing on naming. Something that will calculate the total so be named to reflect that it is not a simple accessor. Something like `computeEncodedLength`.

**Comment by agmt** [comment]
@mjpt777 noticed. New function names are: `static computeLength(...)` (to predict message length before encoding) and `decodeLength() const` (to find length in the beginning of decoding).

**Comment by mjpt777** [comment]
I see you were fixing some warnings in addition to this. I've picked those up independently.

**Comment by agmt** [comment]
I've rebased on master

**Comment by mjpt777** [comment]
Be good to get @tmontgomery view on this.

**Pull request merged**
