### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/real-logic/simple-binary-encoding/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/real-logic/simple-binary-encoding).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by mjpt777** [comment]
I'll give it a try for a while. Thanks.

**Comment by mjpt777** [comment]
I fixed the alerts but the link is not updated. How often does this refresh?

**Comment by mjpt777** [comment]
@xcorail It has been two days since I fixed the alerts yet the badge still says they are active. Is there an issue on your side?

**Comment by xcorail** [comment]
You're right, latest commit analysed is e8f1d56 ... Let me check with the support team.

**Comment by xcorail** [comment]
Apparently there have been many activity (PRs to analyse) yesterday and that caused a small backlog in our daily repo poll job. The latest poll on your repo is 2 days ago, before your commits. The support team triggered a poll of your repo, and it should be analysed soon.

**Pull request merged**
