### PR TITLE
dotnet core support

### PR DESCRIPTION
**Pull request by markmcdowell**
Update to:

- build against netstandard 1.3 (lowest version of net standard required)
- build against net45
- added csharpbuild.cmd (similar to cppbuild.cmd) to restore, build and run tests
- corrected nuspec for multiple dotnet versions

### CODE REVIEW

**Comment by mjpt777** [comment]
Thanks! It would be good to get a review from @odeheurles or @billsegall on this.

**Comment by billsegall** [comment]
The patch addresses something on the roadmap and I'd love to see it integrated. There are a bunch of improvements here.

I tried the following:
git clone git@github.com:real-logic/simple-binary-encoding.git
cd simple-binary-encoding
git fetch origin pull/456/head:dn
git checkout dn
gradlew
gradlew generatecsharpcodecs
cd csharp
csharpbuild.cmd

The build then proceeds until I see:
error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\MSTest.TestAdapter.1.1.17\build\net45\MSTest.TestAdapter.props

Once I've opened the solution and built from there then csharpbuild.cmd works. 

I think we can accept the PR and  look to fix the build script from clean checkout separately.

Bill.

**Comment by markmcdowell** [comment]
Let me fix that, it should really work.

**Comment by markmcdowell** [comment]
Now builds from clean checkout.

**Comment by mjpt777** [comment]
Thanks

**Pull request merged**
