### PR TITLE
Warn instead of error on signed numInGrp, check for minValue < 0

### PR DESCRIPTION
**Pull request by kdkavanagh**
Relates to comment on #615.  Allow signed numInGrp and validate that the minValue is > 0

### CODE REVIEW

**Comment by mjpt777** [comment]
The type must be unsigned according to the specification.

**Comment by kdkavanagh** [comment]
Is this materially different than #609?  I don't see the harm in flagging it with a warning but still allowing it to overcome java's unsigned type limitation specifically - All code properly implementing the spec (i.e minValue) should handle this correctly.

**Comment by kdkavanagh** [comment]
Thanks!

**Comment by mjpt777** [comment]
You made a good point :-)

**Pull request merged**
