### PR TITLE
[python] simplify handling of fixed length char arrays [behavior change]

### PR DESCRIPTION
**Pull request by tfgm-bud**
Get or set fixed length char arrays as a single string vs getting each character individually.

### CODE REVIEW

**Comment by mjpt777** [comment]
Python now supported for RC3.

**Comment by tfgm-bud** [comment]
@mjpt777 I'm confused by this.  Looks like python is NOT supported for RC3 at all.  Am I missing something?  -- Bud

**Comment by mjpt777** [comment]
If someone is willing to submit a python port then we will be happy to accept it. @tmontgomery and I only have the time to do C++ and Java.

**Comment by tfgm-bud** [comment]
@mjpt777 OK.  Your comment above said that Python was **NOW** supported.  Hence my confusion.  

If I get some time, I'll try to re implement the python code generation back into the real-logic decoder.

In the meantime, if anyone needs a python based decoder, we have open sourced our python-based SBE decoder:

  https://github.com/tfgm/sbedecoder

For performance reasons, most people would be better off with your C++ or Java decoder but it is an option.

-- Bud

**Comment by mjpt777** [comment]
Typo :-)

**Pull request closed without merging**
